import Head from "next/head";

import Inicio from "../components/seccion/Inicio";
import Instructores from "../components/seccion/Instructores";
import Ofertas from "../components/seccion/Ofertas";
import Planes from "../components/seccion/Planes";
import Imc from "../components/seccion/Imc";
import Contacto from "../components/seccion/Contacto";
import Menu from "../components/Menu";
import BtonTop from "../components/btonTop";
import Spinner from "../components/spinner";

import { useState, useEffect } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 2000);

    return () => clearTimeout(timer); //
  }, []);

  return (
    <div>
      <Head>
        <title>Triforce Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ico.svg" />
      </Head>

      {loading ? (
        <Spinner />
      ) : (
        <main>
          <Menu />
          <Inicio />
          <Ofertas />
          <Planes />
          <Instructores />
          <Imc />
          <Contacto />

          <BtonTop />
        </main>
      )}
    </div>
  );
}
